_commit: v2.8.1
_src_path: gh:quokkify/project-toolkit
components: []
docker: false
project_name: Compose Health Check Action
release_please: false
renovate: true
renovate_config_repository: quokkify/renovate-presets
renovate_presets:
- default
- github-actions
- docker
toolkit_version: v2.8.1
