_commit: v2.20.1
_src_path: https://github.com/quokkify/project-toolkit.git
allure_report: false
codeql: true
codeql_languages: []
components: []
docker: false
project_name: Compose Health Check Action
release_please: false
renovate: true
renovate_config_repository: quokkify/renovate-presets
renovate_presets:
  - default
  - github-actions
  - docker
toolkit_version: v2.20.1
