name: customproject

services:
  web:
    image: busybox:1.38@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
    stop_grace_period: 1s
    command: >
      sh -c "
        echo 'web started';
        touch /tmp/web_ready;
        exec tail -f /dev/null
      "
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/web_ready"]
      interval: 200ms
      timeout: 200ms
      retries: 20
      start_period: 0s
